[package]
name = "widgets"
version = "0.1.0"
edition = "2021"
authors = ["Florian Blasius <flovanpt@posteo.de>"]
license = "MIT"
description = "Example uusign book_flip and co_widgets"
publish = false
repository = "https://codeberg.org/flovansl/slint_extensions"
build = "build.rs"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
book_flip = { path = "../../widgets/book_flip", default-features = false }
co_widgets = { path = "../../widgets/co_widgets", default-features = false }
slint = { version = "0.3.1", default-features = false }
rp-pico = { version = "0.5", optional = true }
slint_rpi_pico = { path = "../../platform_support/slint_rpi_pico", optional = true }

[build-dependencies]
slint-build = "0.3.1"

[features]
default = ["slint/default", "book_flip/default", "co_widgets/default", "std"]
std = []
pico = ["slint_rpi_pico", "slint/libm", "slint/unsafe-single-threaded"]

# Remove the `#wasm#` to uncomment the wasm build.
# This is commented out by default because we don't want to build it as a library by default
# The CI has a script that does sed "s/#wasm# //" to generate the wasm build.

#wasm# [lib]
#wasm# crate-type = ["cdylib"]
#wasm# path = "main.rs"
#wasm#
#wasm# [target.'cfg(target_arch = "wasm32")'.dependencies]
#wasm# wasm-bindgen = { version = "0.2" }
#wasm# web-sys = { version = "0.3", features=["console"] }
#wasm# console_error_panic_hook = "0.1.5"